sentry:
  dsn: "{SENTRY_DSN}"
  release:
    name: "{SENTRY_RELEASE_NAME}"
# This one is optional ... only if you want to use ai-story command
openAi:
  token: ...
amqp:
  url: "{AMQP_URL}"
discord:
    token: "{MTAwNjEzNzY0NTU2ODYzOTAxMQ.G2v9mD.MQqJttficL3yEx_TiPwSnOTfsX38YihSxh-MNU}"
deploy:
  port: "{PORT}"
mongo:
  uri: "${MONGO_URI}"
